swagger: '2.0'
info:
  title: weather
  description: Weather API for retrieving whether
  version: 1.0.0
host: weather.apigateway.sgwash.cloud.goog
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
paths:
  /weather:
    get:
      summary: retrieve weather status
      operationId: "1"
      x-google-backend:
        address: https://weather-7w5grnntvq-uc.a.run.app/weatherstatus
      security:
        - api_key: []
      responses:
        '200':
          description: success
          schema:
            type: string